Create test configuration for "/{GovStackInstance}/{memberClass}/{memberCode}/{applicationCode}/getOpenAPI" endpoint
GovStackWorkingGroup/bb-information-mediator pull request #14
Opened 2023-02-15 16:24 UTC by mgrochalskisoldevelo

Created mocks and Cucumber tests for getOpenAPI endpoint.

**Description**
Create test configuration for /{GovStackInstance}/{memberClass}/{memberCode}/{applicationCode}/getOpenAPI endpoint from https://github.com/GovStackWorkingGroup/bb-information-mediator/blob/main/api/govstack_im_service_metadata_api-0.3-swagger.json .This should include all the steps that are pointed out in the parent ticket.

TICKET: https://govstack-global.atlassian.net/browse/TECH-189

2023-02-16 11:35 UTC, KarolinaKopacz requested changes

2023-02-16 11:35 UTC, KarolinaKopacz commented on test/features/get_open_api.feature
> +    Then User receives a resonse
```suggestion
    Then User receives a response
```

2023-02-16 11:35 UTC, KarolinaKopacz commented on test/features/get_open_api.feature
> +    And The response should be returned in a timely manner
I suggest to change the order of AND. First "...should be returned in a timely manner", then check the response status, then header content-type or similar and at the end json schema :)

2023-02-16 11:35 UTC, KarolinaKopacz commented on test/features/get_open_api.feature
> +    Then User receives a resonse
typo

2023-02-16 11:35 UTC, KarolinaKopacz commented on test/features/support/get_open_api.js
> +  () => ''
Why empty string?

2023-02-17 08:17 UTC, KarolinaKopacz approved these changes

2023-02-20 10:31 UTC, aleksander-reitsakas requested changes
getOpenApi has one query parameter serviceCode

2023-02-23 11:26 UTC, aleksander-reitsakas requested changes
Here also _.:- alowed

2023-02-23 11:28 UTC, KarolinaKopacz requested changes

2023-02-23 11:28 UTC, KarolinaKopacz commented on test/features/support/get_open_api.js
> +// Scenario: Unable to retrieve the openAPI description of the specified REST service because of missing serviceCode parameter
There is no code below. If the step what you use here is defined in line 67-69 then better to write this scenario title above it, somehow merge it or write comment below saying where the code is written

2023-02-27 10:05 UTC, KarolinaKopacz approved these changes

2023-02-28 13:31 UTC, aleksander-reitsakas approved these changes

2023-02-28 14:04 UTC, merged