TECH-478: Update GET /{GovStackInstance}/{memberClass}/{memberCode}/{applicationCode}/listMethods
GovStackWorkingGroup/bb-information-mediator pull request #19
Opened 2023-03-16 16:25 UTC by KarolinaKopacz

Need to update tests for /{GovStackInstance}/{memberClass}/{memberCode}/{applicationCode}/listMethods endpoint.

TICKET: https://govstack-global.atlassian.net/browse/TECH-478

2023-03-17 11:13 UTC, mgrochalskisoldevelo requested changes

2023-03-17 11:13 UTC, mgrochalskisoldevelo commented on test/openAPI/features/list_methods.feature
> +    And The listMethods endpoint response should have content-type header
Please specify value of the header

2023-03-17 11:13 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/helpers/helpers.js
> +    key: 'Accept',
```suggestion
    key: 'content-type',
```

2023-03-17 11:13 UTC, mgrochalskisoldevelo commented on test/openAPI/features/list_methods.feature
>      Given Wants to retrieve the list of REST services and endpoints for a service provider
empty line between scenario and given for consistency

2023-03-17 11:13 UTC, mgrochalskisoldevelo commented on test/openAPI/features/list_methods.feature
> +    Given Wants to retrieve the list of REST services and endpoints for a service provider
empty line between scenario and given for consistency

2023-03-17 11:13 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/list_methods.js
> +      .withHeaders(acceptHeader.key, acceptHeader.value)
let's just check the response header if it's content-type application/json; charset=utf-8

2023-03-17 11:13 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/list_methods.js
> +      .should.have.header('content-type', acceptHeader.value);
```suggestion
      .should.have.header(acceptHeader.key, acceptHeader.value);
```
After change in the helpers file

2023-03-17 11:13 UTC, mgrochalskisoldevelo commented on test/openAPI/features/list_methods.feature
> +    When User sends GET request with given "serviceId" as serviceId, required path params and header
I'd propose: 
```suggestion
    When User sends GET request with given "serviceId1" as serviceId, "identifier" as GovStackInstance "identifier" as memberClass "alp4aNum3r1c" as memberCode "alp4aNum3r1c" as applicationCode
```
Those values will be rows from 1st row of Examples from next scenario. This way we won't need to write 2 methods corresponding to When in .js file

If it repeats with other feature file we can name it a bit different. Maybe User calls listMethods endpoint with given... ?

2023-03-17 11:13 UTC, mgrochalskisoldevelo commented on test/openAPI/features/list_methods.feature
>    Scenario: Successfully retrieved the list of REST services and endpoints for a service provider
```suggestion
  Scenario Outline: Successfully retrieved the list of REST services and endpoints for a service provider
```

2023-03-17 14:22 UTC, aleksander-reitsakas approved these changes

2023-03-17 16:51 UTC, mgrochalskisoldevelo requested changes

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on examples/mock/mockoon-bb-information-mediator.json
> +              "value": "application/json",
this is not necessary.

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on examples/mock/mockoon-bb-information-mediator.json
> +              "value": "^([a-zA-Z][a-zA-Z\\\\d_:\\\\-.]*)$",
```suggestion
              "value": "^([a-zA-Z][a-zA-Z\\d_:\\-.]*)$",
```

Please change regex in mockoon to ```^([a-zA-Z][a-zA-Z\d_:\-.]*)$```

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on test/openAPI/features/list_methods.feature
> +    When User sends GET request with given "serviceId1" as serviceId, "identifier" as GovStackInstance "identifier" as memberClass "alp4aNum3r1c" as memberCode "alp4aNum3r1c" as applicationCode
Now i see that there is ```,``` after ```serviceId```. Maybe:  
```suggestion
    When User sends GET request with given "serviceId1" as serviceId, "identifier" as GovStackInstance, "identifier" as memberClass, "alp4aNum3r1c" as memberCode and "alp4aNum3r1c" as applicationCode
```
or without

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on test/openAPI/features/list_methods.feature
> +    When User sends GET request with given "serviceId" as serviceId, "<GovStackInstance>" as GovStackInstance "<memberClass>" as memberClass "<memberCode>" as memberCode "<applicationCode>" as applic
As previous suggestion

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/list_methods.js
> +Then('User receives a response from the listMethods endpoint', async () => {
unnecessary curly brackets

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/list_methods.js
> +  () => {
unnecessary curly brackets

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/list_methods.js
> +Then('The listMethods endpoint response should have status 200', () => {
unnecessary curly brackets

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/list_methods.js
> +  () => {
unnecessary curly brackets

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/list_methods.js
> +Then('The listMethods endpoint response should match json schema', () => {
unnecessary curly brackets

2023-03-17 16:51 UTC, mgrochalskisoldevelo commented on test/openAPI/features/list_methods.feature
> +  Scenario: Successfully retrieved the list of REST services and endpoints for a service provider
```suggestion
  Scenario: Successfully retrieved the list of REST services and endpoints for a service provider smoke type test
```

2023-03-20 12:36 UTC, mgrochalskisoldevelo approved these changes

2023-03-20 12:36 UTC, merged