TECH-867: fixed for gherkin tests
GovStackWorkingGroup/bb-information-mediator pull request #23
Opened 2023-09-26 11:38 UTC by lruzicki

Ticket:
https://govstack-global.atlassian.net/browse/TECH-867

**Description**
Changes:
1. test/openAPI/docker/entrypoint.sh
Modified cucumber-js command for multiple output formats.
2. test/openAPI/features/allowed_methods.feature
Included Information-Mediator-Client header in GET requests.
3. test/openAPI/features/list_clients.feature, test/openAPI/features/allowed_methods.feature, and test/openAPI/features/list_methods.feature
Refactored content-type header verification.
4. test/openAPI/features/list_methods.feature
Added X-GovStack-Client header in GET requests.
5. test/openAPI/features/support/helpers/helpers.js
Defined Information-Mediator-Client header.
6. test/openAPI/features/support/allowed_methods.js and test/openAPI/features/support/list_methods.js
Implemented headers in GET requests.

2023-09-29 10:48 UTC, dborowiecki requested changes

2023-09-29 10:48 UTC, dborowiecki commented on test/openAPI/features/allowed_methods.feature
> +    When The GET request with given Information-Mediator-Client header, "serviceId1" as serviceId, "identifier" as GovStackInstance, "identifier" as memberClass, "alp4aNum3r1c" as memberCode and "alp
I have some improvement ideas for this.
First, I think we're missing the actual header value as it's used later on in the tests. 

Second is there are quite some values in the scenario step, which might affect readability. I suggest changing them to more readable format of data table. 
For example: 
```gherkin
When I send a GET request with:
  | Header                     | Value                  |
  | Information-Mediator-Client| value                  |

And the payload contains:
  | Parameter       | Value       |
  | serviceId       | serviceId1  |
  | GovStackInstance| identifier  |
  | memberClass     | identifier  |
  | memberCode      | alp4aNum3r1c|
  | applicationCode | alp4aNum3r1c|

``` 

and implementation like: 
```js
When('I send a GET request with:', function (dataTable) {
    // Convert DataTable to a JavaScript object
    headers = dataTable.rowsHash();
   //...
});

When('the payload contains:', function (dataTable) {
    // Convert DataTable to a JavaScript object
    payload = dataTable.rowsHash();
   //...
});
```

I think it will also be the case for plenty of other scenarios and I don't think it should be a priority to change everything, but we could think of it as a proof of concept. Let me know your thoughts.

2023-09-29 10:48 UTC, dborowiecki commented on test/openAPI/features/allowed_methods.feature
> +    When The GET request with given Information-Mediator-Client header, "<serviceId>" as serviceId, "<GovStackInstance>" as GovStackInstance, "<memberClass>" as memberClass, "<memberCode>" as memberC
Please add missing header value in here

2023-10-02 12:09 UTC, lruzicki commented on test/openAPI/features/allowed_methods.feature
> +    When The GET request with given Information-Mediator-Client header, "serviceId1" as serviceId, "identifier" as GovStackInstance, "identifier" as memberClass, "alp4aNum3r1c" as memberCode and "alp
I agree, we have plenty of those parameters so it is unreadable when the line is too long. It is a good idea to make it in this way. We can also make it more generic and append headers and parameters straight from this table like:
`When('I send a GET request with:', function (dataTable) {
  const headers = dataTable.rowsHash();
  if (headers.Header) delete headers.Header;
  
  specAllowedMethods.get(baseUrl);
  for (const key in headers) {
    specAllowedMethods.withHeaders(key, headers[key]);
  }
});

When('The payload contains:', function (dataTable) {
  const payload = dataTable.rowsHash();
  if (payload.Parameter) delete payload.Parameter;
  
  const serviceId = payload.serviceId;
  delete payload.serviceId;
  specAllowedMethods
      .withPathParams(payload)
      .withQueryParams(serviceId, serviceId);
});`

2023-10-02 12:09 UTC, lruzicki commented on test/openAPI/features/allowed_methods.feature
> +    When The GET request with given Information-Mediator-Client header, "<serviceId>" as serviceId, "<GovStackInstance>" as GovStackInstance, "<memberClass>" as memberClass, "<memberCode>" as memberC
done

2023-10-02 12:23 UTC, dborowiecki approved these changes

2023-10-02 12:23 UTC, merged